### ISSUE TITLE
Ограниченное количество рабочих мест в помещении

### ISSUE THREAD

**Issue by 0anion0** [solodyagin/inventory#10]
Доброе время суток. 

При настройке обнаружил ограниченное количество рабочих мест в помещении, точнее добавлять сотрудников можно сколько угодно(даже по несколько раз), но отображаются только 5 строк и нельзя переключить страницу списка как это сделано в таблице **Помещения**

https://github.com/solodyagin/inventory/blob/792b2883a92e8080ca7e7d46d201382e3239eb31/app/views/places/index.php#L78

**Comment by solodyagin** [comment]
Доброго времени суток.
Спасибо за найденный недочёт. Постараюсь исправить в ближайшее время

**Comment by 0anion0** [comment]
Там на самом деле везде где есть подтаблица стоит ограничение в 5 строк и
нельзя переключить на следующие 5 строк. Но, есть места где эта подтаблица
высотой в 5 строк и там есть прокрутка, но всё рано всего 5 строк

пн, 16 мар. 2020 г., 23:01 Sergey Solodyagin <notifications@github.com>:
